#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Wallpaper
feh --bg-fill /home/augusto/Pictures/pexels-fauxels-3183198.jpg

# Polybar
~/.config/polybar/./launch.sh

# Source .zshrc
#source ~/.zshrc

# Dual Monitor
~/.screenlayout/./monitors.sh

# Rounded borders Picom
picom --experimental-backends &
bspc config border_width 0

# Mouse
xsetroot -cursor_name left_ptr &
